name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Set the GitHub API Token as an environment variable for React build
    - name: Set GitHub API Token
      run: echo "REACT_APP_STATS_API_TOKEN=${{ secrets.STATS_API_TOKEN }}" >> $GITHUB_ENV

    # Step 5: Build the React application
    - name: Build the project
      run: npm run build

    # Step 6: Deploy the built files to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
